import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { defineConfig } from "vitepress";

interface SidebarItem {
  text: string;
  link?: string;
  collapsed?: boolean;
  items?: SidebarItem[];
}

/**
 * Load the sidebar generated by typedoc-vitepress-theme and normalise its links so VitePress
 * can match them. The plugin emits Windows-flavoured paths like
 * `/docs-site\\api/classes\\Foo.md` — strip the docs root prefix, swap backslashes, and drop
 * the `.md` extension (we run with `cleanUrls: true`).
 */
function loadApiSidebar(): SidebarItem[] {
  const sidebarFile = resolve(__dirname, "../api/typedoc-sidebar.json");
  let raw: SidebarItem[];
  try {
    raw = JSON.parse(readFileSync(sidebarFile, "utf8")) as SidebarItem[];
  } catch {
    return [];
  }
  const normalize = (item: SidebarItem): SidebarItem => {
    const next: SidebarItem = { ...item };
    if (next.link !== undefined) {
      let link = next.link.replace(/\\/g, "/");
      link = link.replace(/^\/?docs-site\/api\//, "/api/");
      link = link.replace(/\.md$/, "");
      next.link = link;
    }
    if (next.items) next.items = next.items.map(normalize);
    return next;
  };
  return raw.map(normalize);
}

export default defineConfig({
  title: "@loontail/minecraft-kit",
  description: "Stateless TypeScript Minecraft launcher library and interactive CLI.",
  // GitHub Pages serves the site under https://loontail.github.io/minecraft-kit/.
  // Every asset URL must be prefixed with this path; an empty / "/" base would 404 in
  // production while still working in `npm run docs:dev`.
  base: "/minecraft-kit/",
  cleanUrls: true,
  lastUpdated: false,
  ignoreDeadLinks: false,
  markdown: {
    lineNumbers: false,
    theme: { light: "github-light", dark: "github-dark" },
  },
  themeConfig: {
    nav: [
      {
        text: "Getting Started",
        link: "/getting-started/installation",
        activeMatch: "^/getting-started/",
      },
      { text: "Guides", link: "/guides/library-usage", activeMatch: "^/guides/" },
      { text: "API", link: "/api/" },
    ],
    sidebar: {
      "/getting-started/": [
        {
          text: "Getting Started",
          items: [
            { text: "Installation", link: "/getting-started/installation" },
            { text: "Quickstart", link: "/getting-started/quickstart" },
          ],
        },
      ],
      "/guides/": [
        {
          text: "Library",
          items: [
            { text: "Library usage", link: "/guides/library-usage" },
            { text: "Targets", link: "/guides/targets" },
            { text: "Install", link: "/guides/install" },
            { text: "Verify & repair", link: "/guides/verify-repair" },
            { text: "Launch", link: "/guides/launch" },
          ],
        },
        {
          text: "Account",
          items: [
            { text: "Authentication", link: "/guides/auth" },
            { text: "Skins", link: "/guides/skins" },
          ],
        },
        {
          text: "Loaders",
          items: [
            { text: "Vanilla / Minecraft", link: "/guides/minecraft" },
            { text: "Fabric", link: "/guides/fabric" },
            { text: "Forge", link: "/guides/forge" },
            { text: "Java runtime", link: "/guides/runtime" },
          ],
        },
        {
          text: "CLI",
          items: [{ text: "mckit", link: "/guides/cli" }],
        },
        {
          text: "Reference",
          items: [
            { text: "Errors", link: "/guides/errors" },
            { text: "Events", link: "/guides/events" },
            { text: "Enums & types", link: "/guides/types" },
          ],
        },
        {
          text: "Concepts",
          items: [
            { text: "Architecture", link: "/guides/architecture" },
            { text: "Stateless design", link: "/guides/stateless" },
            { text: "Security model", link: "/guides/security" },
            { text: "Limitations", link: "/guides/limitations" },
          ],
        },
      ],
      "/api/": [{ text: "API Overview", link: "/api/" }, ...loadApiSidebar()],
    },
    outline: { level: [2, 3], label: "On this page" },
    search: { provider: "local" },
    footer: { message: "MIT License", copyright: "© 2026 loontail" },
  },
});
